const game = [
    {
        id:1,
        name:'breakout',
        url:'/brick',
        description:'A layer of bricks lines the top third of the screen and the goal is to destroy them all by repeatedly bouncing a ball off a paddle into them.',
        logo:'https://mancunion.com/wp-content/uploads/sites/6/break-out.jpg',
        players:[
            {
                id:1,
                name:'John',
                bestScore:300,
                profile:"https://s3-ap-northeast-1.amazonaws.com/peatix-files/user/5562732/240administrator-male.png"
            },
            {
                id:2,
                name:'Doe',
                bestScore:200,
                profile:"https://s3-ap-northeast-1.amazonaws.com/peatix-files/user/5562732/240administrator-male.png"
            },
            {
                id:3,
                name:'Williams',
                bestScore:400,
                profile:"https://s3-ap-northeast-1.amazonaws.com/peatix-files/user/5562732/240administrator-male.png",
            },
        ]
    },
    {
        id:2,
        name:'snake',
        url:'/snake',
        description:'The game continues until the snake dies. A snake dies by either (1) running into the edge of the board, or (2) by running into its own tail. The final score is based on the number of apples eaten by the snake.',
        logo:'https://firebasestorage.googleapis.com/v0/b/fir-imagestore-5410f.appspot.com/o/logos%2Fsnake.jpeg?alt=media&token=f233d34f-d30c-43ee-9d08-951c4b1e5a31',
        players:[
            {
                id:1,
                name:'Johns',
                bestScore:100,
                profile:"https://s3-ap-northeast-1.amazonaws.com/peatix-files/user/5562732/240administrator-male.png"
            },
            {
                id:2,
                name:'Doed',
                bestScore:200,
                profile:"https://s3-ap-northeast-1.amazonaws.com/peatix-files/user/5562732/240administrator-male.png"
            },
            {
                id:3,
                name:'smith',
                bestScore:300,
                profile:"https://s3-ap-northeast-1.amazonaws.com/peatix-files/user/5562732/240administrator-male.png"
            },
        ]
    },
    {
        id:3,
        name:'flappy bird',
        url:'/flappy',
        description:'A side-scroller where the player controls a bird, attempting to fly between columns of green pipes without hitting them.',
        logo:'https://is4-ssl.mzstatic.com/image/thumb/Purple71/v4/d5/b0/76/d5b0769d-85a4-a43f-fa7d-80f6fcb2fda7/source/512x512bb.jpg',
        players:[
            {
                id:1,
                name:'John',
                bestScore:100,
                profile:"https://s3-ap-northeast-1.amazonaws.com/peatix-files/user/5562732/240administrator-male.png"
            },
            {
                id:2,
                name:'Doe',
                bestScore:200,
                profile:"https://s3-ap-northeast-1.amazonaws.com/peatix-files/user/5562732/240administrator-male.png"
            },
            {
                id:3,
                name:'Williams',
                bestScore:300,
                profile:"https://s3-ap-northeast-1.amazonaws.com/peatix-files/user/5562732/240administrator-male.png"
            },
        ]
    },
    {
        id:4,
        name:'TICTACTOE',
        url:'/tictactoe',
        description:'A game in which two players alternately put Xs and Os in compartments of a figure formed by two vertical lines crossing two horizontal lines and each tries to get a row of three Xs or three Os.',
        logo:'https://firebasestorage.googleapis.com/v0/b/fir-imagestore-5410f.appspot.com/o/logos%2Ftictactoe.jpeg?alt=media&token=12c08de1-194e-45dd-8f7d-1b137f4ed694',
        players:[
            {
                id:1,
                name:'Johns',
                bestScore:100,
                profile:"https://s3-ap-northeast-1.amazonaws.com/peatix-files/user/5562732/240administrator-male.png"
            },
            {
                id:2,
                name:'Doed',
                bestScore:200,
                profile:"https://s3-ap-northeast-1.amazonaws.com/peatix-files/user/5562732/240administrator-male.png"
            },
            {
                id:3,
                name:'smith',
                bestScore:300,
                profile:"https://s3-ap-northeast-1.amazonaws.com/peatix-files/user/5562732/240administrator-male.png"
            },
        ]
    },
    {
        id:5,
        name:'rock paper scissor',
        url:'/rockpaper',
        description:'A rock beats scissors, scissors beat paper by cutting it, and paper beats rock by covering it',
        logo:'https://firebasestorage.googleapis.com/v0/b/fir-imagestore-5410f.appspot.com/o/logos%2Frockpapsicss.jpeg?alt=media&token=567f0549-f9eb-4786-9dab-72a139ed7b11',
        players:[
            {
                id:1,
                name:'Johns',
                bestScore:100,
                profile:"https://s3-ap-northeast-1.amazonaws.com/peatix-files/user/5562732/240administrator-male.png"
            },
            {
                id:2,
                name:'Doed',
                bestScore:200,
                profile:"https://s3-ap-northeast-1.amazonaws.com/peatix-files/user/5562732/240administrator-male.png"
            },
            {
                id:3,
                name:'smith',
                bestScore:300,
                profile:"https://s3-ap-northeast-1.amazonaws.com/peatix-files/user/5562732/240administrator-male.png"
            },
        ]
    },
]

export default game